### ISSUE TITLE
ERROR [ExceptionHandler] Nest can't resolve dependencies of the CategoryController (?). Please make sure that the argument Function at index [0] is available in the CategoryModule context.

### ISSUE THREAD

**Issue by MrOxMasTer** [nestjs/typeorm#2156] opened 2024-12-20 21:45 UTC
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

10.0.2 -> 10.0.2

### Describe the regression

Don't work

First time I encounter this behavior when connecting orm, when I could not create any table even. This was my first and last time I used this orm and this library:

```
[Nest] 37380  - 21.12.2024, 00:43:24   ERROR [ExceptionHandler] Nest can't resolve dependencies of the CategoryController (?). Please make sure that the argument Function at index [0] is available in the CategoryModule context.

Potential solutions:
- Is CategoryModule a valid NestJS module?     
- If Function is a provider, is it part of the current CategoryModule?
- If Function is exported from a separate @Module, is that module imported within CategoryModule?
  @Module({
    imports: [ /* the Module containing Function */ ]
  })

Error: Nest can't resolve dependencies of the CategoryController (?). Please make sure that the argument Function at index [0] is available in the CategoryModule context.

Potential solutions:
- Is CategoryModule a valid NestJS module?     
- If Function is a provider, is it part of the current CategoryModule?
- If Function is exported from a separate @Module, is that module imported within CategoryModule?
  @Module({
    imports: [ /* the Module containing Function */ ]
  })

    at Injector.lookupComponentInParentModules (C:\Users\user\Desktop\coursework OOP\oop2\oop2\node_modules\.pnpm\@nestjs+core@10.4.15_@nestjs+common@10.4.15_class-transformer@0.5.1_class-validator@0.14.1_re_ilhxcld7a72vuoqnfqd7fueu7a\node_modules\@nestjs\core\injector\injector.js:262:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Injector.resolveComponentInstance (C:\Users\user\Desktop\coursework OOP\oop2\oop2\node_modules\.pnpm\@nestjs+core@10.4.15_@nestjs+common@10.4.15_class-transformer@0.5.1_class-validator@0.14.1_re_ilhxcld7a72vuoqnfqd7fueu7a\node_modules\@nestjs\core\injector\injector.js:215:33)
    at async resolveParam (C:\Users\user\Desktop\coursework OOP\oop2\oop2\node_modules\.pnpm\@nestjs+core@10.4.15_@nestjs+common@10.4.15_class-transformer@0.5.1_class-validator@0.14.1_re_ilhxcld7a72vuoqnfqd7fueu7a\node_modules\@nestjs\core\injector\injector.js:129:38)
    at async Promise.all (index 0)
    at async Injector.resolveConstructorParams (C:\Users\user\Desktop\coursework OOP\oop2\oop2\node_modules\.pnpm\@nestjs+core@10.4.15_@nestjs+common@10.4.15_class-transformer@0.5.1_class-validator@0.14.1_re_ilhxcld7a72vuoqnfqd7fueu7a\node_modules\@nestjs\core\injector\injector.js:144:27)
    at async Injector.loadInstance (C:\Users\user\Desktop\coursework OOP\oop2\oop2\node_modules\.pnpm\@nestjs+core@10.4.15_@nestjs+common@10.4.15_class-transformer@0.5.1_class-validator@0.14.1_re_ilhxcld7a72vuoqnfqd7fueu7a\node_modules\@nestjs\core\injector\injector.js:70:13)      
    at async Injector.loadController (C:\Users\user\Desktop\coursework OOP\oop2\oop2\node_modules\.pnpm\@nestjs+core@10.4.15_@nestjs+common@10.4.15_class-transformer@0.5.1_class-validator@0.14.1_re_ilhxcld7a72vuoqnfqd7fueu7a\node_modules\@nestjs\core\injector\injector.js:89:9)     
    at async C:\Users\user\Desktop\coursework OOP\oop2\oop2\node_modules\.pnpm\@nestjs+core@10.4.15_@nestjs+common@10.4.15_class-transformer@0.5.1_class-validator@0.14.1_re_ilhxcld7a72vuoqnfqd7fueu7a\node_modules\@nestjs\core\injector\instance-loader.js:68:13
    at async Promise.all (index 0)
```

### Minimum reproduction code

```ts

@Module({
	imports: [TypeOrmModule.forFeature([Category])],
	controllers: [CategoryController],
	providers: [CategoryService],
})
export class CategoryModule {}


@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: 'localhost',
      port: 5432,
      username: 'postgres',
      password: 'postgres',
      database: 'oop',
      entities: [],
      synchronize: true,
      // synchronize: true, // FIXME: nest.js documents
      // entities: [Category],
      // autoLoadEntities: true,
      }),
      CategoryModule,
    // OrderModule,
    // OrderItemModule,
    // ProductModule,
    // WarehouseModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

async function bootstrap() {
  const PORT = process.env.PORT || 5001;
  const app = await NestFactory.create(AppModule);

  // app.enableCors({
  // 	origin: [
  // 		"http://localhost:3000",
  // 		"http://192.168.0.100:3000",
  // 		"http://192.168.0.101:3000",
  // 	],
  // 	methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
  // 	credentials: true,
  // });

  app.useGlobalPipes(new ValidationPipe({ transform: true }));

  await app.listen(PORT, () => console.log(`SERVER STARTED: PORT=${PORT}`));
}
bootstrap();
```

### Expected behavior

No error

**Comment by jmcdo29** [comment] 2024-12-20 21:51
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by MrOxMasTer** [comment] 2024-12-20 22:07
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

https://github.com/MrOxMasTer/oop2

**Comment by jmcdo29** [comment] 2024-12-20 22:42
You shouldn't be using type imports for cakes that will be injected by the framework. This is not a bug with nest but a limitation of typescript and a side effect of how decorators work

**Closed** 2024-12-20 22:42 UTC
Labels: needs triage

**Comment by MrOxMasTer** [comment] 2024-12-20 22:45
> You shouldn't be using type imports for cakes that will be injected by the framework. This is not a bug with nest but a limitation of typescript and a side effect of how decorators work

That's what I figured. What needs to be changed and what was the problem. What “cakes” are we talking about

**Comment by jmcdo29** [comment] 2024-12-20 22:46
"cakes" -> values

Typo from my phone

**Comment by MrOxMasTer** [comment] 2024-12-20 22:47
![image](https://github.com/user-attachments/assets/599fcb03-5bf9-42e2-bd2b-4bcd0198fc83)

**Comment by MrOxMasTer** [comment] 2024-12-20 22:53
> You shouldn't be using type imports for cakes that will be injected by the framework. This is not a bug with nest but a limitation of typescript and a side effect of how decorators work

I have them used in my code specifically solely as types. How should I know for this implicit behavior?

**Comment by micalevisk** [comment] 2024-12-21 01:26
@MrOxMasTer read the docs. This is mentioned in the FAQ.

This is a well-known limitation of typescript introspection. But yeah, you must be really familiar with TS to know this.

**Comment by MrOxMasTer** [comment] 2024-12-21 07:49
> @MrOxMasTer read the docs. This is mentioned in the FAQ.
> 
> This is a well-known limitation of typescript introspection. But yeah, you must be really familiar with TS to know this.

It's marvelous. As long as I've known ts, he surprises me every time. I've already written one project on nest.js and this is the first time I've heard of such a problem.
